In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("diabetes2.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [33]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [34]:
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64


In [35]:
df.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Outcome                      0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221071                  0.137337   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.436783  0.392573                  0.183928   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.042163  0.036242                  0.033561   
Outcome                   0.130548  0.292695                  0.173844   

                               Age   Outcome  
Pregnancies               0.544341  0.221898  
Glucose                   0.263514  0.466581  
BloodPressure             0.239528  0.065068  
SkinThickness            -0.113970  0.074752  
Insulin                  -0.042163  0.130548  
BMI                       0.036242  0.292695  
DiabetesPedigreeFunction  0.033561  0.173844  
Age                       1.000000  0.238356  
Outcome                   0.238356  1.000000

In [36]:
X=df.drop("Outcome",axis=1)


In [37]:
y=df[['Outcome']]

In [38]:
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [39]:
y

Outcome
0          1
1          0
2          1
3          0
4          1
..       ...
763        0
764        0
765        0
766        1
767        0

[768 rows x 1 columns]

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [41]:
print(X.shape)
print(y.shape)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(768, 8)
(768, 1)
(576, 8)
(192, 8)
(576, 1)
(192, 1)


In [42]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
X_train=st.fit_transform(X_train)
X_test=st.fit_transform(X_test)

In [43]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [44]:
y_pred=classifier.predict(X_test)

In [45]:
y_pred

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [46]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[103,  27],
       [ 19,  43]], dtype=int64)

In [47]:
from sklearn.metrics import classification_report,accuracy_score

In [48]:
res=classification_report(y_test,y_pred)
print("Classification Report:")
print(res)

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.79      0.82       130
           1       0.61      0.69      0.65        62

    accuracy                           0.76       192
   macro avg       0.73      0.74      0.73       192
weighted avg       0.77      0.76      0.76       192



In [49]:
result=accuracy_score(y_test,y_pred)
print("Accuracy:",result)

Accuracy: 0.7604166666666666


In [50]:
from sklearn.metrics import accuracy_score,recall_score,f1_score
Accuracy=accuracy_score(y_test,y_pred)

In [51]:
Accuracy

0.7604166666666666

In [52]:
Specificity =recall_score(y_test,y_pred, pos_label=0)
Sensitivity_recall = recall_score(y_test, y_pred)
Specificity =recall_score(y_test, y_pred, pos_label=0)
F1_score =f1_score(y_test, y_pred)

In [53]:
print(Specificity)
print(Sensitivity_recall)
print(Specificity)
print(F1_score)

0.7923076923076923
0.6935483870967742
0.7923076923076923
0.6515151515151515


In [54]:
from sklearn.metrics import mean_squared_error
res1=mean_squared_error(y_test,y_pred)
res1

0.23958333333333334

In [55]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nAccuracy Score:")
print(accuracy_score(y_test, y_pred))


Confusion Matrix:
[[103  27]
 [ 19  43]]

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.79      0.82       130
           1       0.61      0.69      0.65        62

    accuracy                           0.76       192
   macro avg       0.73      0.74      0.73       192
weighted avg       0.77      0.76      0.76       192


Accuracy Score:
0.7604166666666666


In [56]:
#Decision tree regressor

In [57]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
predit_r2_score = r2_score(y_test,y_pred)
print(predit_r2_score) # 1.0 = 100%

-0.09578163771712145


In [58]:
# predicting the actual and predicted value is same.. 0.0 = same
print("Mean Squared Error : " , mean_squared_error(y_test,y_pred))

Mean Squared Error :  0.23958333333333334


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("diabetes2.csv")
df
df.describe()
print(df.isnull().sum())
df.corr()
X=df.drop("Outcome",axis=1)
y=df[['Outcome']]
y
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)
print(X.shape)
print(y.shape)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
X_train=st.fit_transform(X_train)
X_test=st.fit_transform(X_test)
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
y_pred
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm
from sklearn.metrics import classification_report,accuracy_score
res=classification_report(y_test,y_pred)
print("Classification Report:")
print(res)
result=accuracy_score(y_test,y_pred)
print("Accuracy:",result)
from sklearn.metrics import accuracy_score,recall_score,f1_score
Accuracy=accuracy_score(y_test,y_pred)
Accuracy
print(Specificity)
print(Sensitivity_recall)
print(Specificity)
print(F1_score)
from sklearn.metrics import mean_squared_error
res1=mean_squared_error(y_test,y_pred)
res1
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nAccuracy Score:")
print(accuracy_score(y_test, y_pred))
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
predit_r2_score = r2_score(y_test,y_pred)
print(predit_r2_score) # 1.0 = 100%



Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64
(768, 8)
(768, 1)
(576, 8)
(192, 8)
(576, 1)
(192, 1)
Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.79      0.82       130
           1       0.61      0.69      0.65        62

    accuracy                           0.76       192
   macro avg       0.73      0.74      0.73       192
weighted avg       0.77      0.76      0.76       192

Accuracy: 0.7604166666666666


NameError: name 'Specificity' is not defined

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# load the dataset
df=pd.read_csv("diabetes2.csv")

# display the dataset
df

# generate descriptive statistics of the dataset
df.describe()

# check for missing values in the dataset
print(df.isnull().sum())

# compute the correlation matrix of the dataset
df.corr()

# separate the input features (X) and the target variable (y)
X=df.drop("Outcome",axis=1)
y=df[['Outcome']]

# split the dataset into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

# print the shapes of the datasets
print(X.shape)
print(y.shape)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

# perform feature scaling on the training and testing sets
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
X_train=st.fit_transform(X_train)
X_test=st.fit_transform(X_test)

# train a decision tree classifier on the training set
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)

# make predictions on the testing set
y_pred=classifier.predict(X_test)

# compute the confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

# compute the classification report and accuracy score
from sklearn.metrics import classification_report,accuracy_score
res=classification_report(y_test,y_pred)
print("Classification Report:")
print(res)
result=accuracy_score(y_test,y_pred)
print("Accuracy:",result)

# compute the accuracy, specificity, sensitivity, and F1 score
from sklearn.metrics import accuracy_score,recall_score,f1_score
Accuracy=accuracy_score(y_test,y_pred)
Specificity = cm[0,0]/(cm[0,0]+cm[0,1])
Sensitivity_recall = recall_score(y_test, y_pred)
F1_score = f1_score(y_test,y_pred)

print("Accuracy:",Accuracy)
print("Specificity:",Specificity)
print("Sensitivity/Recall:",Sensitivity_recall)
print("F1 Score:",F1_score)

# compute the mean squared error
from sklearn.metrics import mean_squared_error
res1=mean_squared_error(y_test,y_pred)
res1

# compute the confusion matrix, classification report, and accuracy score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nAccuracy Score:")
print(accuracy_score(y_test, y_pred))

# compute the R2 score
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
predit_r2_score = r2_score(y_test,y_pred)
print(predit_r2_score) # 1.0 = 100%


Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64
(768, 8)
(768, 1)
(576, 8)
(192, 8)
(576, 1)
(192, 1)
Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.79      0.82       130
           1       0.61      0.69      0.65        62

    accuracy                           0.76       192
   macro avg       0.73      0.74      0.73       192
weighted avg       0.77      0.76      0.76       192

Accuracy: 0.7604166666666666
Accuracy: 0.7604166666666666
Specificity: 0.7923076923076923
Sensitivity/Recall: 0.6935483870967742
F1 Score: 0.6515151515151515
Confusion Matrix:
[[103  27]
 [ 19  43]]

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.79  